services:

  frontend:
    image: node:20
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:3000:3000"
    command: "npm run dev"

