name: Deploy

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/smart-fit-frontend
            git checkout develop
            git stash
            git pull --rebase
            rm -rf node_modules
            rm package-lock.json
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            rm -rf .output
            npm install
            npm run build
            cp .env .output/server/.env
            pm2 kill Smartfit
            pm2 start
